FROM ubi8
USER root
COPY osnoise/cmd.sh /root
COPY common-libs /root/common-libs
RUN curl -L -o /etc/yum.repos.d/rtla-experimental.repo http://rats-builder.lab.eng.bos.redhat.com/repos/rtla/rhel8/rtla-experimental.repo \
    && yum install -y rtla \
    && yum -y install which tmux rsync \
      python3 numactl-devel kernel-devel kernel-tools numactl-libs \
    && ln -s $(which python3) /usr/local/bin/python \
    && yum clean all && rm -rf /var/cache/yum \
    && curl -L -o /root/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64 \
    && chmod 777 /root/dumb-init \
    && chmod 777 /root/cmd.sh
WORKDIR /root
ENTRYPOINT ["/root/dumb-init", "--"]
CMD ["/root/cmd.sh"]
