FROM fedora:latest
USER root
COPY osnoise/cmd.sh /root
COPY common-libs /root/common-libs
RUN dnf -y update && dnf -y install libtraceevent-devel libtracefs-devel python3-docutils git make gcc wget bzip2 && dnf clean all
RUN wget https://bristot.me/files/rtla/tarball/rtla-6.3.0.tar.bz2 \
    && tar -jxvf rtla-6.3.0.tar.bz2 && cd rtla-6.3.0 && make \
    && make install && cd && rm -rf rtla-6.3.0
RUN dnf -y install which tmux python3 numactl-devel kernel-devel kernel-tools numactl-libs \
    && ln -s $(which python3) /usr/local/bin/python \
    && dnf clean all && rm -rf /var/cache/yum \
    && curl -L -o /root/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.2/dumb-init_1.2.2_amd64 \
    && chmod 777 /root/dumb-init \
    && chmod 777 /root/cmd.sh
WORKDIR /root
ENTRYPOINT ["/root/dumb-init", "--"]
CMD ["/root/cmd.sh"]
