apiVersion: v1 
kind: Pod 
metadata:
  name: timerlat 
  annotations:
    cpu-load-balancing.crio.io: "disable"
    irq-load-balancing.crio.io: "disable"
    cpu-quota.crio.io: "disable"
spec:
  # Map to the correct performance class in the cluster (from PAO)
  # Identify class names with "oc get runtimeclass"
  runtimeClassName: performance-openshift-node-performance-profile
  restartPolicy: Never 
  containers:
  - name: container-perf-tools 
    #image: quay.io/jlelli/timerlat-experimental
    image: quay.io/jlelli/timerlat-upstream
    imagePullPolicy: Always
    # Request and Limits must be identical for the Pod to be assigned to the QoS Guarantee
    resources:
      requests:
        memory: "200Mi"
        cpu: "16"
      limits:
        memory: "200Mi"
        cpu: "16"
    env:
    - name: tool
      value: "timerlat"
    - name: DURATION
      value: "12h"
    - name: MAXLATENCY
      value: "18"
    - name: EXTRA
      #value: " "
      value: "-e sched:sched_switch -e sched:sched_wakeup -e sched:sched_migrate_task -e irq -e irq_vectors -e timer -e workqueue -e ipi:ipi_entry -e ipi:ipi_exit -e ipi:ipi_raise -e ipi:ipi_send_cpu --trigger='stacktrace' -e ipi:ipi_send_cpumask --trigger='stacktrace' -e context_tracking"
      #value: "-e sched:sched_switch -e sched:sched_wakeup -e sched:sched_migrate_task -e irq -e irq_vectors -e timer -e workqueue -e ipi"
      #value: "-e sched:sched_switch -e sched:sched_wakeup -e sched:sched_migrate_task -e irq -e irq_vectors -e timer -e workqueue -e probe:sched_rt_handler --trigger='stacktrace' -e probe:do_start_rt_bandwidth --trigger='stacktrace' -e ipi"
      #value: "-e sched:sched_switch -e sched:sched_wakeup --trigger='stacktrace if comm ~ \"kworker*\"' -e sched:sched_migrate_task -e irq -e irq_vectors -e timer -e workqueue"
      #value: "-e sched:sched_switch -e sched:sched_wakeup --trigger='stacktrace' -e sched:sched_migrate_task -e irq -e irq_vectors -e timer -e workqueue -e ipi -e rcu:rcu_quiescent_state_report -e rcu:rcu_exp_grace_period -e rcu:rcu_exp_funnel_lock -e rcu:rcu_dyntick"
    - name: delay
      value: "60"
    # # Following setting not required in OCP4.6+
    # - name: DISABLE_CPU_BALANCE
    #   value: "y"
    #   # DISABLE_CPU_BALANCE requires privileged=true
    securityContext:
      privileged: true
      #capabilities:
      #  add:
      #    - SYS_NICE
      #    - IPC_LOCK
      #    - SYS_RAWIO
    volumeMounts:
    - mountPath: /dev/cpu_dma_latency
      name: cstate
  volumes:
  - name: cstate
    hostPath:
      path: /dev/cpu_dma_latency
  #nodeSelector:
  #  node-role.kubernetes.io/worker-rt: ""
  
