apiVersion: v1 
kind: Pod 
metadata:
  name: osnoise 
  annotations:
    cpu-load-balancing.crio.io: "disable"
    irq-load-balancing.crio.io: "disable"
    cpu-quota.crio.io: "disable"
spec:
  # Map to the correct performance class in the cluster (from PAO)
  # Identify class names with "oc get runtimeclass"
  runtimeClassName: performance-openshift-node-performance-profile
  restartPolicy: Never 
  containers:
  - name: container-perf-tools 
    image: quay.io/jlelli/osnoise-experimental
    imagePullPolicy: Always
    # Request and Limits must be identical for the Pod to be assigned to the QoS Guarantee
    resources:
      requests:
        memory: "200Mi"
        cpu: "16"
      limits:
        memory: "200Mi"
        cpu: "16"
    env:
    - name: tool
      value: "osnoise"
    - name: DURATION
      value: "1m"
    - name: MAXLATENCY
      value: "20"
    - name: EXTRA
      value: "-e sched:sched_switch -e sched:sched_wakeup -e sched:sched_migrate_task -e irq -e irq_vectors -e timer"
    - name: delay
      value: "0"
    # # Following setting not required in OCP4.6+
    # - name: DISABLE_CPU_BALANCE
    #   value: "y"
    #   # DISABLE_CPU_BALANCE requires privileged=true
    securityContext:
      privileged: true
      #capabilities:
      #  add:
      #    - SYS_NICE
      #    - IPC_LOCK
      #    - SYS_RAWIO
    volumeMounts:
    - mountPath: /dev/cpu_dma_latency
      name: cstate
  volumes:
  - name: cstate
    hostPath:
      path: /dev/cpu_dma_latency
  #nodeSelector:
  #  node-role.kubernetes.io/worker-rt: ""
  
